name: Release Workflow
timeout-minutes: 240
on:
  release:
    types:
      - created
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up working directory
        run: cd ${{ github.workspace }}

      - uses: actions/checkout@v3

      - name: Install Python and gdown
        run: |
          sudo apt-get install -y python3
          pip install gdown

      - name: Download files
        run: |
          gdown https://drive.google.com/uc?id=1hA4SyQFEgotNIQSCyVzdwZuuB-bdGCn2

      - name: Unzip arxiv_abstracts.zip
        run: unzip arxiv_abstracts.zip

      - name: Create abstracts directory
        run: mkdir abstracts

      - name: Move .parquet files to abstracts directory
        run: mv arxiv_abstracts/*.parquet abstracts/

      - name: Create converted directory
        run: mkdir converted
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build Go project
        run: go build -o main .

      - name: Run Go binary
        run: ./main

      - name: recursively list files
        run: ls -R

      - name: Create zip file
        run: zip -r converted.zip converted

      - name: Get existing release body
        id: get_release_body
        run: |
          echo "::set-output name=body::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_path }} | jq -r '.body')"

      - name: Upload release artifact
        uses: svenstaro/upload-release-action@v2
        with:
          file: converted.zip
          tag: ${{ github.ref }}
          body: |
            ${{ steps.get_release_body.outputs.body }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
